title: Suhas Nama # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
    Backend Software Engineer
  <br><br>
  <a href="mailto:suhasnama23@gmail.com">suhasnama23@gmail.com </a>
  <br>
  <a href="https://drive.google.com/file/d/1xyebESQ4GI--1TT6vmWLWLa_ZJe6EJZ2/view">Resume</a>
  <br>
  
theme: jekyll-theme-minimal
