title: \t\t\t\tSuhas Nama # your name (or website title) here
logo: "/profile_v2.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  &nbsp;&nbsp;&nbsp;&nbsp;FullStack Software Engineer
  <br><br>
  <a href="mailto:suhasnama23@gmail.com">suhasnama23@gmail.com </a>
theme: jekyll-theme-minimal
